version: '3.4'

services:
  ningodokja:
    image: ningodokja
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./cmd/bot/.env.production
    environment:
      - APP_ENVIRONMENT=production
      - APP_REDIS_ADDR=redis:6379
      - APP_POSTGRES_HOST=postgres
      - APP_POSTGRES_PORT=5432
    depends_on:
      - redis

  postgres:
    image: postgres:13.15
    container_name: ningo_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
