version: '3.4'

services:
  ningodokja:
    image: ningodokja
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
