version: '3.4'

services:
  ningodokja:
    image: ningodokja
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NEWS_CHANNEL_ID=${NEWS_CHANNEL_ID}
      - OLYMPIC_CHANNEL_ID=${OLYMPIC_CHANNEL_ID}
      - OLYMPIC_CHANNEL_FINISHED_ID=${OLYMPIC_CHANNEL_FINISHED_ID}
      - OLYMPIC_CHANNEL_RUNNING_ID=${OLYMPIC_CHANNEL_RUNNING_ID}
      - GUILD_ID=${GUILD_ID}
      - ENVIRONMENT=development
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
