[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:5000 main:app
directory=/app
autostart=true
autorestart=true
user=dokja

[program:background]
command=python main.py
directory=/app
autostart=true
autorestart=true
user=dokja
