FROM docker.io/golang:1.25-bookworm

RUN apt-get update && apt-get install -y \
    libzmq3-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@v1.63.0

WORKDIR /workspace/dokja_orch
